---

- hosts: all
  become: true
  tasks: 

  - name: ensure a container is running
      docker_container:
        name: django
        state: started
        image: "thanhvhv/jenkins"
        pull: true
        ports:
          - "80:8000"
