---
- hosts: server
  become: true
  tasks:
    - name: Install prerequisite packages
      apt:
        name:
        -  software-properties-common
        -  gnupg
        -  apt-transport-https
        -  ca-certificates
    - name: Install prerequisite packages    
      shell: "curl -fsSL https://pgp.mongodb.com/server-7.0.asc |  sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor"
    - name: Install prerequisite packages  
      shell: "echo 'deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list"
    - name: Install MongoDB  
      apt:
        name: mongodb-org
        state: present
        update_cache:  yes