version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    env_file:
      - './.env.sample'
    ports:
      - '${PUBLIC_HTTP_PORT}:80'
      - '${PUBLIC_HTTPS_PORT}:443'
      - '${ADMIN_WEB_PORT}:81'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: ${DB_MYSQL_PORT}
      DB_MYSQL_USER: "${DB_MYSQL_USER}"
      DB_MYSQL_PASSWORD: "${DB_MYSQL_PASSWORD}"
      DB_MYSQL_NAME: "${DB_MYSQL_NAME}"
      DISABLE_IPV6: '${DISABLE_IPV6}'
    volumes:
      - ~/data:/data
      - ~/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - npm-internal
      - npm-nw

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    env_file:
      - './.env.sample'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MARIADB_AUTO_UPGRADE: '${MARIADB_AUTO_UPGRADE}'
      MYSQL_INITDB_SKIP_TZINFO: '1'
    volumes:
      - ~/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - npm-internal
networks:
  npm-internal:
  npm-nw:
    external: true
